// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6tHskC6DgfH3D-Vc3CNjBtfSBT6vcYw',
    appId: '1:30004554015:web:f3032a39d6ddf3f5b1e82a',
    messagingSenderId: '30004554015',
    projectId: 'jobapp-14c52',
    authDomain: 'jobapp-14c52.firebaseapp.com',
    databaseURL: 'https://jobapp-14c52-default-rtdb.firebaseio.com',
    storageBucket: 'jobapp-14c52.firebasestorage.app',
    measurementId: 'G-0MLT93KQHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAQSotcKrcbRPmDm1CVzn1AkSNnzqwIOc',
    appId: '1:30004554015:android:60e9fca4b6589741b1e82a',
    messagingSenderId: '30004554015',
    projectId: 'jobapp-14c52',
    databaseURL: 'https://jobapp-14c52-default-rtdb.firebaseio.com',
    storageBucket: 'jobapp-14c52.firebasestorage.app',
  );
}
